# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nsasate | Dance Studio
owner: Ricardo Lara
email: alejandro.elara@live.com
description: > # this means to ignore newlines until "baseurl:"
  N'salsat, academia de baile para todos los niveles, ven y enamorate del baile!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb

# menu:
# - {name: Maestros, value: '5'}
# - {name: Estudiantes, value: '50'}
# - {name: Coreografías, value: '14'}
# - {name: Presentaciones, value: '15'}




# Build settings
markdown: kramdown

port: 4000
